title: PasseRR's Blog
description: My Personal Blog

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

url: "https://jekyll-blog-theme"
baseurl: ""
paginate: 15
per_page: 15
paginate_path: "/page/:num/"

highlighter: rouge
#markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough

gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
