title: PasseRR's Blog
description: My Personal Blog

enableTags: true
tagarray: [ ]

collections:
  project:
    output: true
    permalink: /project/:path/

url: ""
baseurl: ""
permalink: /:name:output_ext
paginate: 15
per_page: 15
paginate_path: "/page/:num/"

highlighter: rouge
#markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough

gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

# trello 留言板
# key
bmob-app-id: 3f2b257266b4f2f0ebf13e96776cb0f3
# token
bmob-rest-key: 346e810c8fe7cfccd6d403fb86c96489c9d1716555d87b9f28c5cfe8f2d055fd
# card id
bmob-message-table: 632d5e7da375620029986942

# theme-cdn: https://cdn.jsdelivr.net/gh/PasseRR/jekyll-blog-theme
# theme-cdn: https://fastly.jsdelivr.net/gh/PasseRR/jekyll-blog-theme
# theme-cdn: https://gcore.jsdelivr.net/gh/PasseRR/jekyll-blog-theme
theme-cdn: .

compress_html:
  clippings: all
  comments: [ "<!-- ", " -->" ]
  endings: all

plugins:
  - jekyll-toc
  - jekyll-paginate
  - jekyll-relative-links
