title: PasseRR's Blog
description: My Personal Blog

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

url: "https://jekyll-blog-theme"
baseurl: ""
paginate: 15
per_page: 15
paginate_path: "/page/:num/"

highlighter: rouge
#markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink
    - tables
    - strikethrough

gems:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

# 留言板配置
bmob-app-id: e71fdd8d5b1f139b1da542a1e3a2ad09
bmob-rest-key: 3f399f018571ea78c9bc3245c58a8c0e
bmob-message-table: message

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
